[2024-09-27T00:17:23.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-27T00:17:24.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-27T00:17:17.154026+00:00 [queued]>
[2024-09-27T00:17:24.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-27T00:17:17.154026+00:00 [queued]>
[2024-09-27T00:17:24.230+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-27T00:17:24.341+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_api> on 2024-09-27 00:17:17.154026+00:00
[2024-09-27T00:17:24.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=95613) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-27T00:17:24.420+0000] {standard_task_runner.py:63} INFO - Started process 95621 to run task
[2024-09-27T00:17:24.366+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_postgres_pandas_dag_with_decorators', 'read_data_from_api', 'manual__2024-09-27T00:17:17.154026+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpnx2yl09y']
[2024-09-27T00:17:25.437+0000] {standard_task_runner.py:91} INFO - Job 110: Subtask read_data_from_api
[2024-09-27T00:17:25.676+0000] {task_command.py:426} INFO - Running <TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-27T00:17:17.154026+00:00 [running]> on host 5e909a8df6c4
[2024-09-27T00:17:26.233+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_postgres_pandas_dag_with_decorators' AIRFLOW_CTX_TASK_ID='read_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T00:17:17.154026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T00:17:17.154026+00:00'
[2024-09-27T00:17:26.234+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-27T00:17:26.289+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-09-27T00:17:26.378+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-27T00:17:26.387+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_prueba.py", line 42, in read_data_from_api
    URL_VAR= URL_BASE+ VARIABLE +"/"+inicio_str+"/"+final_str
             ~~~~~~~~^~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
[2024-09-27T00:17:26.481+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=example_postgres_pandas_dag_with_decorators, task_id=read_data_from_api, run_id=manual__2024-09-27T00:17:17.154026+00:00, execution_date=20240927T001717, start_date=20240927T001724, end_date=20240927T001726
[2024-09-27T00:17:26.572+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 110 for task read_data_from_api (can only concatenate str (not "int") to str; 95621)
[2024-09-27T00:17:26.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-27T00:17:27.252+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T00:17:27.273+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
