[2024-09-28T16:00:34.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T16:00:35.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employees.create_employees_table scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-28T16:00:35.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employees.create_employees_table scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-28T16:00:35.950+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T16:00:36.347+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_employees_table> on 2024-09-27 00:00:00+00:00
[2024-09-28T16:00:36.638+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=822) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-28T16:00:36.640+0000] {standard_task_runner.py:63} INFO - Started process 833 to run task
[2024-09-28T16:00:36.629+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_employees', 'create_employees_table', 'scheduled__2024-09-27T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmplx8y2k2q']
[2024-09-28T16:00:36.733+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask create_employees_table
[2024-09-28T16:00:37.896+0000] {task_command.py:426} INFO - Running <TaskInstance: process_employees.create_employees_table scheduled__2024-09-27T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-09-28T16:00:39.239+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employees' AIRFLOW_CTX_TASK_ID='create_employees_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-27T00:00:00+00:00'
[2024-09-28T16:00:39.242+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-28T16:00:39.250+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS employees (
                "Serial Number" NUMERIC PRIMARY KEY,
                "Company Name" TEXT,
                "Employee Markme" TEXT,
                "Description" TEXT,
                "Leave" INTEGER
            );
[2024-09-28T16:00:39.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-28T16:00:39.619+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `tutorial_pg_conn` isn't defined
[2024-09-28T16:00:39.711+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=process_employees, task_id=create_employees_table, run_id=scheduled__2024-09-27T00:00:00+00:00, execution_date=20240927T000000, start_date=20240928T160035, end_date=20240928T160039
[2024-09-28T16:00:39.902+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task create_employees_table (The conn_id `tutorial_pg_conn` isn't defined; 833)
[2024-09-28T16:00:40.062+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T16:00:40.184+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-28T16:00:40.415+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T16:00:40.512+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
