[2024-09-26T23:24:20.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-26T23:24:21.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-26T23:24:07.838919+00:00 [queued]>
[2024-09-26T23:24:21.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-26T23:24:07.838919+00:00 [queued]>
[2024-09-26T23:24:21.517+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-26T23:24:23.545+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_api> on 2024-09-26 23:24:07.838919+00:00
[2024-09-26T23:24:23.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_postgres_pandas_dag_with_decorators', 'read_data_from_api', 'manual__2024-09-26T23:24:07.838919+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmplb9q3w_f']
[2024-09-26T23:24:23.724+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask read_data_from_api
[2024-09-26T23:24:23.799+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=94377) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-26T23:24:23.837+0000] {standard_task_runner.py:63} INFO - Started process 94382 to run task
[2024-09-26T23:24:24.343+0000] {task_command.py:426} INFO - Running <TaskInstance: example_postgres_pandas_dag_with_decorators.read_data_from_api manual__2024-09-26T23:24:07.838919+00:00 [running]> on host 5e909a8df6c4
[2024-09-26T23:24:25.765+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_postgres_pandas_dag_with_decorators' AIRFLOW_CTX_TASK_ID='read_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T23:24:07.838919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-26T23:24:07.838919+00:00'
[2024-09-26T23:24:25.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-26T23:24:25.875+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-09-26T23:24:27.585+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1103 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-09-26T23:24:27.671+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-26T23:24:27.690+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_prueba.py", line 52, in read_data_from_api
    df.to_sql(TABLA, conn, schema=schema_name, if_exists='replace', index=False)
                                  ^^^^^^^^^^^
NameError: name 'schema_name' is not defined
[2024-09-26T23:24:27.807+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=example_postgres_pandas_dag_with_decorators, task_id=read_data_from_api, run_id=manual__2024-09-26T23:24:07.838919+00:00, execution_date=20240926T232407, start_date=20240926T232421, end_date=20240926T232427
[2024-09-26T23:24:28.193+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task read_data_from_api (name 'schema_name' is not defined; 94382)
[2024-09-26T23:24:28.325+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-26T23:24:28.622+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T23:24:28.739+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
