[2024-12-02T00:00:13.484+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-02T00:00:13.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data scheduled__2024-12-01T00:00:00+00:00 [queued]>
[2024-12-02T00:00:13.839+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data scheduled__2024-12-01T00:00:00+00:00 [queued]>
[2024-12-02T00:00:13.840+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-02T00:00:13.876+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2024-12-01 00:00:00+00:00
[2024-12-02T00:00:13.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'merge_data', 'scheduled__2024-12-01T00:00:00+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpylk5gpo1']
[2024-12-02T00:00:13.898+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=52022) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T00:00:13.899+0000] {standard_task_runner.py:63} INFO - Started process 52032 to run task
[2024-12-02T00:00:13.901+0000] {standard_task_runner.py:91} INFO - Job 398: Subtask merge_data
[2024-12-02T00:00:13.991+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.merge_data scheduled__2024-12-01T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-12-02T00:00:14.184+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-01T00:00:00+00:00'
[2024-12-02T00:00:14.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-02T00:00:14.210+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-12-02T00:00:14.230+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-02T00:00:14.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-02T00:00:14.249+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=merge_data, run_id=scheduled__2024-12-01T00:00:00+00:00, execution_date=20241201T000000, start_date=20241202T000013, end_date=20241202T000014
[2024-12-02T00:00:14.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-02T00:00:14.381+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T00:00:14.385+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
